//! Generate conformance test vectors for the did:nostr specification.
//!
//! Writes test-vectors.json directly to disk with clean UTF-8 (no BOM)
//! and LF line endings.
//!
//! Run:
//!   cargo run --example generate_test_vectors

use nostr_did::document::{DocumentBuilder, Profile};
use nostr_did_key as key;
use serde::Serialize;
use serde_json::Value;

fn main() {
    let vectors = generate_all_vectors();

    let json = serde_json::to_string_pretty(&vectors).unwrap();
    let normalized = json.replace("\r\n", "\n");

    // Write directly to file — avoids shell pipeline encoding issues
    std::fs::write("test-vectors.json", normalized.as_bytes()).unwrap();
    eprintln!("Wrote test-vectors.json");
}

// ============================================================================
// Test Vectors Structure
// ============================================================================

#[derive(Serialize)]
struct TestVectors {
    #[serde(rename = "spec")]
    spec_name: String,
    version: String,
    description: String,
    #[serde(rename = "generatedBy")]
    generated_by: String,
    vectors: VectorCategories,
}

#[derive(Serialize)]
struct VectorCategories {
    key_transformation: Vec<KeyTransformVector>,
    key_decoding: Vec<KeyDecodingVector>,
    error_cases: Vec<ErrorVector>,
    did_document_generation: Vec<DidDocumentVector>,
}

#[derive(Serialize)]
struct KeyTransformVector {
    name: String,
    description: String,
    input: String,
    output: String,
    #[serde(rename = "roundtrip")]
    roundtrip: bool,
}

#[derive(Serialize)]
struct KeyDecodingVector {
    name: String,
    description: String,
    input: String,
    output: String,
    parity: u8,
}

#[derive(Serialize)]
struct ErrorVector {
    name: String,
    description: String,
    input: String,
    error: String,
}

#[derive(Serialize)]
struct DidDocumentVector {
    name: String,
    description: String,
    input: String,
    output: Value,
}

// ============================================================================
// Vector Generation
// ============================================================================

fn generate_all_vectors() -> TestVectors {
    TestVectors {
        spec_name: "did:nostr".to_string(),
        version: "0.0.12".to_string(),
        description: "Conformance test vectors for the did:nostr method. Generated by the nostr-did Rust implementation (https://crates.io/crates/nostr-did).".to_string(),
        generated_by: "nostr-did v0.1.3 (https://crates.io/crates/nostr-did)".to_string(),
        vectors: VectorCategories {
            key_transformation: generate_key_transform_vectors(),
            key_decoding: generate_key_decoding_vectors(),
            error_cases: generate_error_vectors(),
            did_document_generation: generate_did_document_vectors(),
        },
    }
}

// -------------------------------------------------------------------
// Key Transformation Vectors
// -------------------------------------------------------------------

fn generate_key_transform_vectors() -> Vec<KeyTransformVector> {
    let spec_pubkey = "124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2";

    vec![
        KeyTransformVector {
            name: "spec_example_2_5".to_string(),
            description: "The example public key from section 2.5 of the specification".to_string(),
            input: spec_pubkey.to_string(),
            output: key::public_key_to_multikey(spec_pubkey).unwrap(),
            roundtrip: verify_roundtrip(spec_pubkey),
        },
        KeyTransformVector {
            name: "all_zeros".to_string(),
            description: "All-zero public key (x=0 is a valid secp256k1 x-coordinate -- treated as opaque hex in default mode)".to_string(),
            input: "0000000000000000000000000000000000000000000000000000000000000000".to_string(),
            output: key::public_key_to_multikey(
                "0000000000000000000000000000000000000000000000000000000000000000",
            )
            .unwrap(),
            roundtrip: verify_roundtrip(
                "0000000000000000000000000000000000000000000000000000000000000000",
            ),
        },
        KeyTransformVector {
            name: "all_ones".to_string(),
            description: "All-ones public key (x >= p, not a valid secp256k1 field element -- treated as opaque hex in default mode, rejected with crypto-validation)".to_string(),
            input: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff".to_string(),
            output: key::public_key_to_multikey(
                "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            )
            .unwrap(),
            roundtrip: verify_roundtrip(
                "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
            ),
        },
        KeyTransformVector {
            name: "uppercase_input".to_string(),
            description: "Uppercase hex input should be accepted and normalized to lowercase output".to_string(),
            input: "124C0FA99407182ECE5A24FAD9B7F6674902FC422843D3128D38A0AFBEE0FDD2".to_string(),
            output: key::public_key_to_multikey(
                "124C0FA99407182ECE5A24FAD9B7F6674902FC422843D3128D38A0AFBEE0FDD2",
            )
            .unwrap(),
            roundtrip: true,
        },
        KeyTransformVector {
            name: "mixed_case_input".to_string(),
            description: "Mixed case hex input should be accepted".to_string(),
            input: "124c0fa99407182ece5a24fAD9B7F6674902FC422843d3128d38a0afbee0fdd2".to_string(),
            output: key::public_key_to_multikey(
                "124c0fa99407182ece5a24fAD9B7F6674902FC422843d3128d38a0afbee0fdd2",
            )
            .unwrap(),
            roundtrip: true,
        },
    ]
}

// -------------------------------------------------------------------
// Key Decoding Vectors
// -------------------------------------------------------------------

fn generate_key_decoding_vectors() -> Vec<KeyDecodingVector> {
    let spec_pubkey = "124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2";
    let spec_multikey = key::public_key_to_multikey(spec_pubkey).unwrap();

    // Build an odd-parity multikey for the same x-coordinate.
    // The did:nostr identifier is x-only and parity-agnostic.
    // Canonical Multikey is even-parity 0x02; decoders accept 0x03 for interop.
    let odd_multikey = {
        let raw = decode_hex_32(spec_pubkey);
        let mut compressed = [0u8; 33];
        compressed[0] = 0x03;
        compressed[1..].copy_from_slice(&raw);
        let with_codec = prepend_multicodec(&compressed);
        encode_multibase_base16_lower(&with_codec)
    };

    vec![
        KeyDecodingVector {
            name: "decode_even_parity".to_string(),
            description: "Decode a Multikey with even parity (0x02) -- canonical BIP-340 encoding".to_string(),
            input: spec_multikey,
            output: spec_pubkey.to_string(),
            parity: 2,
        },
        KeyDecodingVector {
            name: "decode_odd_parity".to_string(),
            description: "Decode a Multikey with odd parity (0x03) -- same x-coordinate, other lift. Decoders accept both for interop; BIP-340 canonical decoder rejects odd parity.".to_string(),
            input: odd_multikey,
            output: spec_pubkey.to_string(),
            parity: 3,
        },
    ]
}

// -------------------------------------------------------------------
// Error Cases
// -------------------------------------------------------------------

fn generate_error_vectors() -> Vec<ErrorVector> {
    vec![
        ErrorVector {
            name: "error_hex_too_short".to_string(),
            description: "Hex input shorter than 64 characters".to_string(),
            input: "abc123".to_string(),
            error: "InvalidHexLength".to_string(),
        },
        ErrorVector {
            name: "error_hex_too_long".to_string(),
            description: "Hex input longer than 64 characters".to_string(),
            input: "124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd20000".to_string(),
            error: "InvalidHexLength".to_string(),
        },
        ErrorVector {
            name: "error_hex_empty".to_string(),
            description: "Empty input".to_string(),
            input: "".to_string(),
            error: "InvalidHexLength".to_string(),
        },
        ErrorVector {
            name: "error_invalid_hex_character".to_string(),
            description: "Non-hex character in input".to_string(),
            input: "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg".to_string(),
            error: "InvalidHexCharacter".to_string(),
        },
        ErrorVector {
            name: "error_x_not_field_element".to_string(),
            description: "x-coordinate >= field prime p -- rejected by crypto-validation".to_string(),
            input: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc30".to_string(),
            error: "InvalidPublicKey".to_string(),
        },
        ErrorVector {
            name: "error_odd_parity_in_bip340_decoder".to_string(),
            description: "BIP-340 canonical decoder rejects odd parity".to_string(),
            input: build_odd_parity_multikey("124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2"),
            error: "OddParityNotCanonical".to_string(),
        },
        ErrorVector {
            name: "error_wrong_multicodec".to_string(),
            description: "Multikey with incorrect multicodec prefix".to_string(),
            input: "f000102124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2".to_string(),
            error: "InvalidMulticodec".to_string(),
        },
        ErrorVector {
            name: "error_invalid_multibase_prefix".to_string(),
            description: "Multikey without 'f' prefix".to_string(),
            input: "abc123".to_string(),
            error: "InvalidMultibase".to_string(),
        },
        ErrorVector {
            name: "error_uppercase_multibase_prefix".to_string(),
            description: "Multikey with uppercase 'F' prefix (only lowercase 'f' is valid base16-lower)".to_string(),
            input: key::public_key_to_multikey(
                "124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2",
            )
            .unwrap()
            .to_uppercase(),
            error: "InvalidMultibase".to_string(),
        },
        ErrorVector {
            name: "error_invalid_key_length".to_string(),
            description: "Multikey with truncated key data".to_string(),
            input: "fe70102".to_string(),
            error: "InvalidKeyLength".to_string(),
        },
    ]
}

// -------------------------------------------------------------------
// DID Document Generation Vectors
// -------------------------------------------------------------------

fn generate_did_document_vectors() -> Vec<DidDocumentVector> {
    let did = "did:nostr:124c0fa99407182ece5a24fad9b7f6674902fc422843d3128d38a0afbee0fdd2";

    // Minimal document (section 2.3.1) -- no signed parts, no modified
    let minimal_doc = DocumentBuilder::new().build(did).unwrap();
    let minimal_json = serde_json::to_value(&minimal_doc).unwrap();

    // Enhanced document (section 2.3.2) -- with relays, modified from kind-10002 created_at
    let enhanced_doc = DocumentBuilder::new()
        .with_relay("wss://relay.damus.io")
        .with_relay("wss://nos.lol")
        .with_modified("2025-01-26T15:30:00Z")
        .build(did)
        .unwrap();
    let enhanced_json = serde_json::to_value(&enhanced_doc).unwrap();

    // Complete document (section 2.3.3)
    let profile = Profile {
        name: Some("Alice".to_string()),
        about: Some("Building the decentralized web".to_string()),
        picture: Some("https://example.com/alice.jpg".to_string()),
        nip05: Some("alice@example.com".to_string()),
        lud16: Some("alice@getalby.com".to_string()),
        website: Some("https://alice.example.com".to_string()),
        created_at: Some(1737906600),
    };

    let complete_doc = DocumentBuilder::new()
        .with_relay("wss://relay.damus.io")
        .with_profile(profile)
        .with_also_known_as(vec![
            "https://alice.example.com/#me".to_string(),
            "https://social.example.com/@alice".to_string(),
            "at://alice.bsky.social".to_string(),
        ])
        .with_follows(vec![
            "did:nostr:32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245".to_string(),
            "did:nostr:46fcbe3065eaf1ae7811465924e48923363ff3f526bd6f73d7c184147700e3a8".to_string(),
        ])
        .with_modified("2025-01-26T15:30:00Z")
        .build(did)
        .unwrap();
    let complete_json = serde_json::to_value(&complete_doc).unwrap();

    vec![
        DidDocumentVector {
            name: "minimal_document_2_3_1".to_string(),
            description: "Section 2.3.1 -- Minimal DID Document (offline resolution, verification method only)".to_string(),
            input: did.to_string(),
            output: minimal_json,
        },
        DidDocumentVector {
            name: "enhanced_document_2_3_2".to_string(),
            description: "Section 2.3.2 -- Enhanced DID Document with relay service endpoints".to_string(),
            input: did.to_string(),
            output: enhanced_json,
        },
        DidDocumentVector {
            name: "complete_document_2_3_3".to_string(),
            description: "Section 2.3.3 -- Complete DID Document with profile, alsoKnownAs, and follows".to_string(),
            input: did.to_string(),
            output: complete_json,
        },
    ]
}

// ============================================================================
// Helpers
// ============================================================================

fn verify_roundtrip(hex_pubkey: &str) -> bool {
    if let Ok(multikey) = key::public_key_to_multikey(hex_pubkey) {
        if let Ok(recovered) = key::multikey_to_bip340_pubkey(&multikey) {
            return recovered.to_lowercase() == hex_pubkey.to_lowercase();
        }
    }
    false
}

fn decode_hex_32(hex: &str) -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

fn prepend_multicodec(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + data.len());
    out.extend_from_slice(&[0xe7, 0x01]);
    out.extend_from_slice(data);
    out
}

fn encode_multibase_base16_lower(data: &[u8]) -> String {
    let hex: String = data.iter().map(|b| format!("{b:02x}")).collect();
    format!("f{hex}")
}

fn build_odd_parity_multikey(hex_pubkey: &str) -> String {
    let raw = decode_hex_32(hex_pubkey);
    let mut compressed = [0u8; 33];
    compressed[0] = 0x03;
    compressed[1..].copy_from_slice(&raw);
    let with_codec = prepend_multicodec(&compressed);
    encode_multibase_base16_lower(&with_codec)
}